### ISSUE TITLE
refactor/new features - todo list

### ISSUE THREAD

**Issue by Datzu712** [Datzu712/flask-fullstack-template#13]
- [ ] Refactor poorly bad made templates
- [x] Move js code to another part and make an only main bundle with webpack (and allow typescript files too)
- [ ] implement kubernetes, new relic (prob inside of docker)
- [ ] move database to postgresql (?
- [ ] add unit testing

**Comment by Datzu712** [comment]
+webpack #15
